language: node_js
node_js:
  - "0.10"
services:
  - postgresql
addons:
  postgresql: "9.3"
  sauce_connect: true
notifications:
  email: false
script:
  - npm run syntax
  - npm test
before_script:
  - psql -c 'create database evernode_test;' -U postgres
  - cd test/scripts; ./create-db.sh evernode_test; cd ../..;
  - PORT=9001 node server/index.js&
  - sleep 5
after_script:
  - npm run coveralls
  - npm run e2e
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/evernode_test
    - AWS_BUCKET=mattevernote-test
    - secure: "lwLYGAROpyMWpT1nHY+BgkxyeYREccgb6iK3/MqeBqm9nU2yIHAV5//rh8Me5wpwFT/KimM5aBZIxzbskK8Ynac4gZnezVSJQ6Mq5OdkALB4g8zBkMy2dCWSU6yynEyQqddsXZ/RjkrIl+NOHbHHHL+UYdY5sfbXb5hG2JRmSLw="
    - secure: "Y02siAlXkw739YRUUC4qmLBupcPYvBVZM7pz1jKkaieZHqB8Psn5BDpNBjrvEZ0804jZneuyAwuQ9g7RjiHGJZesLcxkK6rzH0pXAqm1l3k72Z4U48zl6a4IWmRSuBuZasEYoXd/UeTiuWuUMDAi189BVuP3lGcEjaT0Kt6+F5w="
    - secure: "YN9Ca6s5s1x0DGkinryRY1/xKYMko+2fCNyd6HSX3LDWT1Bw9dvgRM10fYA3OxJ1tJ+aJ6UqjTpVwex82j8iKkvowuIOb4qChErVbRpzxMIfJpAeKrxjdbOVNs4XipJ196mr9HeRtiZ5yyfPJkrvSgSog4nKo8HVYkP37QfjROk="
    - secure: "NFBEwqNOy+JNHoS3tLs2d0+hZOuX/QGZPOJd+QDUKNe4oLp5vRCXXxnAdXhd5NlzdZUTwjBAJhZh0MSg3bmaZeC/L1YrPvOWAp1OmEyfuG9eGqVLttYa1M4axGRJoeBX+gP2zUd63EVs2+0ybRwbLT4VFuUDOPjeeUTGckOGafg="
