language: node_js
node_js:
  - "0.10"
services:
  - postgresql
addons:
  postgresql: "9.3"
notifications:
  email: false
script:
  - npm run syntax
  - npm test
before_script:
  - psql -c 'create database evernode_test;' -U postgres
  - cd test/scripts; ./create-db.sh evernode_test; cd ../..;
after_script:
  - npm run coveralls
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/evernode_test
    - AWS_BUCKET=mattevernote-test
    - secure: "lwLYGAROpyMWpT1nHY+BgkxyeYREccgb6iK3/MqeBqm9nU2yIHAV5//rh8Me5wpwFT/KimM5aBZIxzbskK8Ynac4gZnezVSJQ6Mq5OdkALB4g8zBkMy2dCWSU6yynEyQqddsXZ/RjkrIl+NOHbHHHL+UYdY5sfbXb5hG2JRmSLw="
    - secure: "Y02siAlXkw739YRUUC4qmLBupcPYvBVZM7pz1jKkaieZHqB8Psn5BDpNBjrvEZ0804jZneuyAwuQ9g7RjiHGJZesLcxkK6rzH0pXAqm1l3k72Z4U48zl6a4IWmRSuBuZasEYoXd/UeTiuWuUMDAi189BVuP3lGcEjaT0Kt6+F5w="
